services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vacation-management-api
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11.8
    container_name: vm-api_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vacation_management_api
      MYSQL_USER: angel
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vm-api_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: angel
      PMA_PASSWORD: 12345678
    depends_on:
      - db

volumes:
  dbdata:
